import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import 'package:ingridio/logic/recipe_serializer.dart';
import 'package:ingridio/models/recipe.dart';

/// Per-user store of saved recipes.
///
/// Stores the FULL Recipe object in Firestore so recipes generated by Gemini
/// (which don't exist in MockData) can still be displayed in the Saved list.
class SavedRecipesStore extends ChangeNotifier {
  SavedRecipesStore._();

  static final SavedRecipesStore instance = SavedRecipesStore._();

  final Map<String, Recipe> _recipes = <String, Recipe>{};

  Set<String> get ids => _recipes.keys.toSet();
  List<Recipe> get recipes => List<Recipe>.unmodifiable(_recipes.values);

  bool isSaved(String recipeId) => _recipes.containsKey(recipeId);

  Future<void> loadForCurrentUser() async {
    _recipes.clear();
    final String? uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid == null) {
      notifyListeners();
      return;
    }
    try {
      final QuerySnapshot<Map<String, dynamic>> snap = await FirebaseFirestore
          .instance
          .collection('users')
          .doc(uid)
          .collection('savedRecipes')
          .get();
      for (final QueryDocumentSnapshot<Map<String, dynamic>> d in snap.docs) {
        final Map<String, dynamic> data = d.data();
        final Map<String, dynamic>? recipeMap =
            data['recipe'] is Map ? Map<String, dynamic>.from(data['recipe'] as Map) : null;
        if (recipeMap != null) {
          final Recipe r = RecipeSerializer.fromMap(recipeMap, fallbackId: d.id);
          _recipes[d.id] = r;
        }
      }
    } on Object {
      // Empty list on failure; UI still works.
    }
    notifyListeners();
  }

  void clearLocal() {
    _recipes.clear();
    notifyListeners();
  }

  Future<void> toggle(Recipe recipe) async {
    final bool wasSaved = _recipes.containsKey(recipe.id);
    if (wasSaved) {
      _recipes.remove(recipe.id);
    } else {
      _recipes[recipe.id] = recipe;
    }
    notifyListeners();

    final String? uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid == null) {
      return;
    }
    final DocumentReference<Map<String, dynamic>> ref = FirebaseFirestore
        .instance
        .collection('users')
        .doc(uid)
        .collection('savedRecipes')
        .doc(recipe.id);
    try {
      if (wasSaved) {
        await ref.delete();
      } else {
        await ref.set(<String, dynamic>{
          'savedAt': FieldValue.serverTimestamp(),
          'recipe': RecipeSerializer.toMap(recipe),
        });
      }
    } on Object {
      // Best-effort sync.
    }
  }
}
